//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Titanic
    {
        public int id { get; set; }
        public Nullable<int> Survived { get; set; }
        public Nullable<int> Passenger_class { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Age { get; set; }
        public string Embarkment { get; set; }
    }
}
